name: Fast Render Video
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./template-helloworld-main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./template-helloworld-main/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Render Video
        # Concurrency 4 rakhi hai takki error na aaye
        run: npx remotion render src/index.ts HelloWorld out.mp4 --fps=30 --concurrency=4 --quiet

      - name: Save Video Artifact
        uses: actions/upload-artifact@v4
        with:
          name: adobe-stock-video
          path: template-helloworld-main/out.mp4
          retention-days: 1
